PASSABLE = 0
IMPASSABLE  = 1

TILE_HEIGHT = 32
TILE_WIDTH = 64
OFFSET_Y = 200

LEFT_CLICK = 1
RIGHT_CLICK = 4

NORTH = 0
SOUTH = 1
EAST = 2
WEST = 3

MAX_ITEMS = 5

ITEM_FOOD = 0
ITEM_POTION = 1

ITEM_LOCATION_FLOOR = 0
ITEM_LOCATION_CHEST = 1

TASK_HALT = 0
TASK_WALK = 1
TASK_ATTACK = 2
TASK_ACTION = 3
TASK_SPEAK = 4
TASK_GOTO = 5


#background/tile numbers for display
WALL_NORTH = 0
WALL_SOUTH = 1
WALL_EAST = 2
WALL_WEST = 3
WALL_IN_CORNER_NORTH = 4
WALL_IN_CORNER_SOUTH = 5
WALL_IN_CORNER_EAST = 6
WALL_IN_CORNER_WEST = 7
WALL_OUT_CORNER_NORTH = 8
WALL_OUT_CORNER_SOUTH = 9
WALL_OUT_CORNER_EAST = 10
WALL_OUT_CORNER_WEST = 11
WALL_DOOR_SOUTH = 12
WALL_DOOR_EAST = 13
WALL_BLOOD_SOUTH = 14
WALL_BLOOD_EAST = 15

IN_TILE_NORM = 16
IN_TILE_CRACKED = 17
IN_TILE_CRACKED_2 = 18
IN_TILE_CRACKED_3 = 19
IN_TILE_EXPLOSION = 20

OUT_TILE = 21
OUT_TILE_PAVE = 22
OUT_TILE_PAVE_NORTH = 23
OUT_TILE_PAVE_SOUTH = 24
OUT_TILE_PAVE_EAST = 25
OUT_TILE_PAVE_WEST = 26

DEMON = 27
TOMBWOOF_NORTH = 28
TOMBWOOF_SOUTH = 29
TOMBWOOF_EAST = 30
TOMBWOOF_WEST = 31

#items and chests

CHEST_NORTH = 32
CHEST_SOUTH = 33
CHEST_EAST = 34
CHEST_WEST = 35

ITEM_FOOD = 36
ITEM_FOOD = 37

#people in the game
PLAYER = 38
ENEMY = 39
NPC = 40



